### PR TITLE
Fix build and update library to 3.1.1

### LINKED ISSUE #1: examples: imgui version assertion triggered in debug build
This only affects the sample application, not the main library.

```
$ zig build run
GL 4.1
OpenGL 4.1 Metal - 89.3, GLSL 4.10
Assertion failed: (sz_io == sizeof(ImGuiIO) && "Mismatched struct layout!"), function DebugCheckVersionAndDataLayout, file imgui.cpp, line 10362.
```

A quick workaround is building in release mode which disables the assertion.

```
$ zig build run -Doptimize=ReleaseFast
```

### LINKED ISSUE #2: Attempting to run samples on Linux (debian 12) results in unexpected C errors
Steps:

1. Clone this repo
2. Run `zig build -Dtest run` from root of repo (on Linux, debian 12, should have all necessary system libs)
3. Get the following errors:
```
~/.cache/zig/p/1220c6750412ebc698694cd08aca4fe87fda8e2df0d4ffa7d33e7de5b8ca5bebb643/src/timer.c:113:17: 
 error: use of undeclared identifier 'CLOCK_MONOTONIC'
 clock_gettime( CLOCK_MONOTONIC, &ts );
                ^
~/.cache/zig/p/1220c6750412ebc698694cd08aca4fe87fda8e2df0d4ffa7d33e7de5b8ca5bebb643/src/timer.c:131:2: 
 error: call to undeclared function 'nanosleep'; ISO C99 and later do not support implicit function declarations
 nanosleep( &ts, NULL );
 ^
```

I also cloned the C Box2D 3.0 repo and built/ran the samples with no problems to confirm it has something to do with the zig build system on linux.

I double checked the C source in the cached files and the necessary imports do _appear_ to be in place to use these declarations

If you have any insights I'd love some help with this. Maybe some special flags zig needs passed to the build system?

### LINKED ISSUE #3: Does not work with latest zig (0.14)
This repo no longer builds with zig 0.14 or later due to the [build.zig.zon format change](https://github.com/ziglang/zig/issues/20178#issuecomment-2147352322)

This should be updated and/or a note should be added to the readme / build.zig stating that it only supports zig 0.13

### PR DESCRIPTION
**Pull request by yzrmn**
This PR:

- fixes #1
  - define `IMGUI_DISABLE_OBSOLETE_FUNCTIONS`
- fixes #2
  - use `-std=gnu17` instead of `-std=c17`
- fixes #3
  - update `build.zig.zon` fields and set minimum zig version to `0.14.1`
- updates Box2D to version 3.1.1
  - also updates and/or canonicalizes dependencies (replace dead glfw repository)
  - specify C/C++ language standard flags for all source files (taken from Box2D CMake files)

Library/Samples:

- [x] zig build -Dtarget=aarch64-linux-gnu
- [x] zig build -Dtarget=aarch64-linux-musl
- [x] zig build -Dtarget=aarch64-macos
- [x] zig build -Dtarget=x86_64-linux-gnu
- [x] zig build -Dtarget=x86_64-linux-musl
- [x] zig build -Dtarget=x86_64-windows
- [x] zig build -Dtest -Dtarget=aarch64-linux-gnu
- [x] zig build -Dtest -Dtarget=aarch64-linux-musl
- [ ] zig build -Dtest -Dtarget=aarch64-macos
    - Compiler error: `unable to find dynamic system library 'objc' using strategy 'paths_first'. searched paths: none`
- [x] zig build -Dtest -Dtarget=x86_64-linux-gnu
- [x] zig build -Dtest -Dtarget=x86_64-linux-musl
- [x] zig build -Dtest -Dtarget=x86_64-windows

Tested:

- [x] zig build run -Dtest -Dtarget=x86_64-linux-gnu
- [ ] zig build run -Dtest -Dtarget=x86_64-linux-musl
    - Runtime error: `GLFW error occurred. Code: 65544. Description: X11: Failed to load Xlib`

### CODE REVIEW

**Comment by yzrmn** [comment]
The main library now builds with:

```
zig build -Dtarget=aarch64-linux
zig build -Dtarget=aarch64-macos
zig build -Dtarget=x86_64-linux
zig build -Dtarget=x86_64-windows
```

Samples also work locally for me with `zig build -Dtest`.

However, I'm having trouble to make this work:

```
zig build -Dtest -Dtarget=aarch64-linux
zig build -Dtest -Dtarget=aarch64-macos
zig build -Dtest -Dtarget=x86_64-linux
zig build -Dtest -Dtarget=x86_64-windows
```

The compiler is complaining about missing GL headers within the samples. For some reason even `zig build -Dtest -Dtarget=x86_64-linux` does not work when `zig build -Dtest` does.

**Comment by yzrmn** [comment]
Most of the targets work now, I have updated the OP. I'm not sure how to fix the remaining targets, but I think the current status is strictly better now. :)

**Comment by yzrmn** [comment]
@hryx @kristoff-it Hey guys :)

I have almost forgotten about this, but now my branch is being forked. Is there a way that we can get this work merged? I could also bump the Zig version up to 0.15.2 and test it again.

**Comment by hryx** [comment]
Hi @yzrmn , thank you for making this and for your patience. It looks good but unfortunately I can't merge it while there is a macOS build error. Weirdly, I get a slightly different error from you, but possibly the same root cause.

```
error: undefined symbol: _OBJC_CLASS_$_CAMetalLayer
    note: referenced by /Users/hryx/src/allyourcodebase/box2d/.zig-cache/o/6e1fffaa961e77cbbd1f0fed5763956f/libglfw.a(cocoa_window.o):_OBJC_CLASSLIST_REFERENCES_$_.363
```

Are you able to debug this? Alternatively, extending this to use Zig 0.15.2 would be fine since we'll need to do that anyway.

**Comment by yzrmn** [comment]
Hi :)

So it looks like that neither https://github.com/allyourcodebase/glfw or https://github.com/zig-gamedev/zglfw is ready for 0.15, however I have fixed the usage of deprecated build API so that the update should go smoother.

> It looks good but unfortunately I can't merge it while there is a macOS build error. Weirdly, I get a slightly different error from you, but possibly the same root cause.

 This is with `-Dtest` right? Did the samples ever work on Mac? Unfortunately I'm only cross-compiling from Linux and am not able to directly tinker on the hardware. I did add some more system libraries from https://github.com/zig-gamedev/system_sdk but now I'm getting errors within some Mac headers:

```
/home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:492:9: error: non-defining declaration of enumeration with a fixed underlying type is only permitted as a standalone declaration; missing list of enumerators?
typedef CF_ENUM(CFIndex, CFComparisonResult) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yz/.cache/zig/p/N-V-__8AAEKaZADb3ixCEWhuTQQxwJaf5IryvX-FnT6rnuIr/backends/imgui_impl_glfw.cpp:110:10: note: in file included from /home/yz/.cache/zig/p/N-V-__8AAEKaZADb3ixCEWhuTQQxwJaf5IryvX-FnT6rnuIr/backends/imgui_impl_glfw.cpp:110:
#include <GLFW/glfw3native.h>   // for glfwGetCocoaWindow()
         ^
/home/yz/.cache/zig/p/glfw-0.0.0-R5AeUm0HGgA_Rlrr9HR91ejkGd-K_JyCjkXz_U3b-jp9/include/GLFW/glfw3native.h:112:13: note: in file included from /home/yz/.cache/zig/p/glfw-0.0.0-R5AeUm0HGgA_Rlrr9HR91ejkGd-K_JyCjkXz_U3b-jp9/include/GLFW/glfw3native.h:112:
   #include <ApplicationServices/ApplicationServices.h>
            ^
/home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:10: note: in file included from /home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
#include <CoreServices/CoreServices.h>
         ^
/home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:10: note: in file included from /home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:
#include <CoreFoundation/CoreFoundation.h>
         ^
/home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:10: note: in file included from /home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
#include <CoreFoundation/CFBase.h>
         ^
/home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:169:55: note: expanded from macro 'CF_ENUM'
#define CF_ENUM(...) __CF_ENUM_GET_MACRO(__VA_ARGS__, __CF_NAMED_ENUM, __CF_ANON_ENUM, )(__VA_ARGS__)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:134:48: note: expanded from macro '__CF_ENUM_GET_MACRO'
#define __CF_ENUM_GET_MACRO(_1, _2, NAME, ...) NAME
                                               ^
/home/yz/.cache/zig/p/system_sdk-0.3.0-dev-alwUNnYaaAJAtIdE2fg4NQfDqEKs7QCXy_qYukAOBfmF/macos12/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:142:75: note: expanded from macro '__CF_NAMED_ENUM'
#define __CF_NAMED_ENUM(_type, _name)     enum __CF_ENUM_ATTRIBUTES _name : _type _name; enum _name : _type
                                                                          ^~~
```

This could have something to do with C++/ObjectiveC/LLVM extensions but I'm not sure how to solve it for now.

**Comment by hryx** [comment]
I did some toying around. All that's needed to fix the original error I saw is linking the right framework:

```zig
samples_exe.linkFramework("QuartzCore");
```

Adding system_sdk smells funny to me. If it's about adding system headers, the GLFW dep already [uses hexops/xcode-frameworks](https://github.com/allyourcodebase/glfw/blob/98607df/build.zig.zon#L13-L17) which is sufficient. (BTW thank you for moving the GLFW dep to allyourcodebase).

**Comment by yzrmn** [comment]
Nice, thanks for investigating on your end :)

> The compiler is complaining about missing GL headers within the samples. For some reason even `zig build -Dtest -Dtarget=x86_64-linux` does not work when `zig build -Dtest` does.

This was why I introduced `system_sdk`. But now that I think about it, I might just have been missing a system package. I will try to remove the dependency again if I find some time the next few days.

**Comment by yzrmn** [comment]
I pushed the changes and  `zig build -Dtest` works on linux (like mentioned before) but cross-compiling the samples generally does not work. This is probably ok because you run the samples locally anyways and the library itself cross-compiles just fine :)

**Comment by hryx** [comment]
Nice, thanks!
